# Funding & Sponsorship Options for MERN Portfolio
# Support the development and maintenance of this project

# GitHub Sponsors - Preferred method
github: [Mostafa-SAID7]

# Buy Me a Coffee - One-time or recurring support
buy_me_a_coffee: mssaid356p

# Ko-fi - Simple one-time donations
ko_fi: MostafaSaid

# Patreon - Monthly recurring support with exclusive perks
patreon: MostafaSaid

# Open Collective - Transparent community funding
open_collective: mern-portfolio

# Liberapay - Recurring donations
liberapay: MostafaSaid

# IssueHunt - Fund specific issues and features
issuehunt: Mostafa-SAID7

# Custom funding links
custom: ['https://github.com/Mostafa-SAID7/Mern-Profile', 'https://www.paypal.me/MostafaSaid']
